import { useEffect, useMemo, useState } from 'react';
import './App.css';
import { getHostnameFromUrl, normalizeDomain } from '../../src/utils/domain';
import { detectCategory, CATEGORY_MAP } from '../../src/utils/categoryDetector';
import { buildPlusAlias, generateAliasSuggestions, isGmailAddress } from '../../src/utils/aliasGenerator';
import { buildGmailFilterQuery, buildGmailSearchUrl, suggestedGmailLabel } from '../../src/utils/gmailFilter';
import { calculateAliasQuality } from '../../src/utils/qualityScore';
import { deleteSiteAlias, loadAliasData, migrateStorageIfNeeded, saveSiteAlias, touchAlias, updateAliasStatus } from '../../src/utils/storage';
import type { AliasCategory, AliasStatus, SiteAlias } from '../../src/types/alias';
import type { AliasSettings } from '../../src/types/settings';

const statuses: AliasStatus[] = ['normal','important','spam','leaked','inactive'];
const categories = Object.keys(CATEGORY_MAP) as AliasCategory[];
const id = () => `${Date.now()}-${Math.random().toString(36).slice(2)}`;
const nowIso = () => new Date().toISOString();

export default function App() {
  const [hostname,setHostname]=useState<string | null>(null);
  const [manualHost,setManualHost]=useState('');
  const [settings,setSettings]=useState<AliasSettings>({baseEmails:[],defaultAliasFormat:'domain',theme:'system',autoDetectCategory:true,autofillFocusedInputFirst:true,fallbackToCopyWhenNoInput:true,gmailAccountIndex:0});
  const [aliases,setAliases]=useState<Record<string,SiteAlias>>({});
  const [toast,setToast]=useState('');
  const [view,setView]=useState<'popup'|'dashboard'|'settings'>('popup');
  const [purpose,setPurpose]=useState('');
  const [search,setSearch]=useState(''); const [statusFilter,setStatusFilter]=useState<'all'|AliasStatus>('all'); const [categoryFilter,setCategoryFilter]=useState<'all'|AliasCategory>('all'); const [sort,setSort]=useState<'lastUsedAt'|'createdAt'|'useCount'>('lastUsedAt');
  const activeHost = hostname || (manualHost.trim() || null);
  const domainKeyword = activeHost ? normalizeDomain(activeHost) : '';
  const category = domainKeyword ? detectCategory(domainKeyword, activeHost || '') : 'other';
  const baseEmail = settings.defaultBaseEmail || settings.baseEmails[0] || '';
  const previous = activeHost ? aliases[activeHost] : undefined;
  const suggestions = useMemo(()=>{ try { return baseEmail && domainKeyword ? generateAliasSuggestions({baseEmail,domainKeyword,category,purpose}) : []; } catch { return []; } },[baseEmail,domainKeyword,category,purpose]);
  const selected = previous?.alias || suggestions[0]?.alias || '';
  const quality = selected ? calculateAliasQuality(previous || suggestions[0]) : null;

  useEffect(()=>{ (async()=>{ await migrateStorageIfNeeded(); const data=await loadAliasData(); setSettings(data.settings); setAliases(data.siteAliases); const [tab]=await browser.tabs.query({active:true,currentWindow:true}); setHostname(tab?.url ? getHostnameFromUrl(tab.url) : null); applyTheme(data.settings.theme); })(); },[]);
  const showToast=(m:string)=>{setToast(m); setTimeout(()=>setToast(''),2200);};
  const applyTheme=(theme:AliasSettings['theme'])=>{ document.documentElement.dataset.theme = theme === 'system' && matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : theme === 'dark' ? 'dark' : 'light'; };
  const persistSettings=async(next:AliasSettings)=>{ setSettings(next); applyTheme(next.theme); await browser.storage.local.set({settings:next, base_email:next.defaultBaseEmail || next.baseEmails[0] || ''}); };
  const save = async(alias=selected)=>{ if(!activeHost || !alias) return; const existing=aliases[activeHost]; const site:SiteAlias={ id:existing?.id || id(), hostname:activeHost, normalizedDomain:domainKeyword, baseEmail, alias, category, note:existing?.note || '', status:existing?.status || 'normal', createdAt:existing?.createdAt || nowIso(), updatedAt:nowIso(), lastUsedAt:existing?.lastUsedAt, useCount:existing?.useCount || 0 }; await saveSiteAlias(site); setAliases({...aliases,[activeHost]:site}); showToast('Saved locally'); };
  const copy = async(alias=selected)=>{ await navigator.clipboard.writeText(alias); if(activeHost && aliases[activeHost]) await touchAlias(activeHost); showToast('Copied'); };
  const autofill = async(alias=selected)=>{ const [tab]=await browser.tabs.query({active:true,currentWindow:true}); let ok=false; if(tab?.id) ok=!!(await browser.tabs.sendMessage(tab.id,{action:'autofillAlias',email:alias}).catch(()=>({ok:false}))).ok; if(!ok && settings.fallbackToCopyWhenNoInput) await navigator.clipboard.writeText(alias); if(activeHost && aliases[activeHost]) await touchAlias(activeHost); showToast(ok?'Autofilled':'No email input found; copied instead'); };
  const exportJson=async()=>{ const data=await loadAliasData(); download(`gmail-alias-toolkit-${Date.now()}.json`, JSON.stringify({version:1,exportedAt:nowIso(),siteAliases:data.siteAliases,settings:data.settings},null,2),'application/json'); };
  const exportCsv=()=>{ const rows=['hostname,normalizedDomain,alias,baseEmail,category,status,note,createdAt,lastUsedAt,useCount',...Object.values(aliases).map(a=>[a.hostname,a.normalizedDomain,a.alias,a.baseEmail,a.category,a.status,a.note||'',a.createdAt,a.lastUsedAt||'',a.useCount].map(v=>`"${String(v).replace(/"/g,'""')}"`).join(','))]; download(`gmail-aliases-${Date.now()}.csv`,rows.join('\n'),'text/csv'); };
  const importJson=()=>{ const input=document.createElement('input'); input.type='file'; input.accept='application/json'; input.onchange=async()=>{ const file=input.files?.[0]; if(!file) return; try{ const parsed=JSON.parse(await file.text()); if(!parsed.siteAliases) throw new Error('Missing siteAliases'); const next={...aliases}; for(const a of Object.values(parsed.siteAliases) as SiteAlias[]){ if(!a.hostname || !a.alias.includes('@')) throw new Error('Invalid alias data'); next[a.hostname]=a; } await browser.storage.local.set({backup_before_import:await loadAliasData(), siteAliases:next, settings:{...settings,...parsed.settings}}); setAliases(next); showToast('Imported JSON'); }catch(e:any){ showToast(`Import failed: ${e.message}`); } }; input.click(); };
  const download=(name:string, content:string, type:string)=>{ const url=URL.createObjectURL(new Blob([content],{type})); const a=document.createElement('a'); a.href=url; a.download=name; a.click(); URL.revokeObjectURL(url); };
  const rows=Object.values(aliases).filter(a=>(statusFilter==='all'||a.status===statusFilter)&&(categoryFilter==='all'||a.category===categoryFilter)&&`${a.hostname} ${a.alias} ${a.note}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=> sort==='useCount' ? b.useCount-a.useCount : String(b[sort]||'').localeCompare(String(a[sort]||'')));

  if(view==='dashboard') return <div className="app"><Header setView={setView}/><section className="card"><h2>Alias dashboard</h2><div className="grid"><input placeholder="Search website, alias, note" value={search} onChange={e=>setSearch(e.target.value)}/><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value as any)}><option value="all">All statuses</option>{statuses.map(s=><option key={s}>{s}</option>)}</select><select value={categoryFilter} onChange={e=>setCategoryFilter(e.target.value as any)}><option value="all">All categories</option>{categories.map(c=><option key={c}>{c}</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value as any)}><option value="lastUsedAt">Sort by last used</option><option value="createdAt">Sort by created date</option><option value="useCount">Sort by use count</option></select></div><div className="actions"><button onClick={exportJson}>Export JSON</button><button onClick={exportCsv}>Export CSV</button><button onClick={importJson}>Import JSON</button></div>{rows.length===0?<p className="muted">No aliases saved yet. Create your first website alias from the popup.</p>:<table><thead><tr><th>Website</th><th>Alias</th><th>Category</th><th>Status</th><th>Last used</th><th>Actions</th></tr></thead><tbody>{rows.map(a=><tr key={a.id}><td>{a.hostname}</td><td>{a.alias}</td><td>{a.category}</td><td>{a.status}</td><td>{a.lastUsedAt?.slice(0,10)||'—'}</td><td><button onClick={()=>copy(a.alias)}>Copy</button><button onClick={()=>autofill(a.alias)}>Autofill</button><select value={a.status} onChange={async e=>{await updateAliasStatus(a.hostname,e.target.value as AliasStatus); setAliases({...aliases,[a.hostname]:{...a,status:e.target.value as AliasStatus}})}}>{statuses.map(s=><option key={s}>{s}</option>)}</select><button onClick={async()=>{const note=prompt('Note',a.note||'')||''; const n={...a,note,updatedAt:nowIso()}; await saveSiteAlias(n); setAliases({...aliases,[a.hostname]:n});}}>Note</button><button onClick={async()=>{await deleteSiteAlias(a.hostname); const n={...aliases}; delete n[a.hostname]; setAliases(n);}}>Delete</button></td></tr>)}</tbody></table>}</section><Privacy/><Toast text={toast}/></div>;
  if(view==='settings') return <div className="app"><Header setView={setView}/><section className="card"><h2>Settings</h2><label>Base Gmail accounts</label><textarea value={settings.baseEmails.join('\n')} onChange={e=>persistSettings({...settings,baseEmails:e.target.value.split('\n').map(x=>x.trim()).filter(Boolean),defaultBaseEmail:e.target.value.split('\n').map(x=>x.trim()).filter(Boolean)[0]})}/>{baseEmail && !isGmailAddress(baseEmail) && <p className="warn">Only Gmail/Googlemail plus addressing is supported.</p>}<label>Default alias format</label><select value={settings.defaultAliasFormat} onChange={e=>persistSettings({...settings,defaultAliasFormat:e.target.value as any})}>{['domain','category-domain','domain-date','domain-random','domain-purpose'].map(f=><option key={f}>{f}</option>)}</select><label>Theme</label><select value={settings.theme} onChange={e=>persistSettings({...settings,theme:e.target.value as any})}><option>system</option><option>light</option><option>dark</option></select><label><input type="checkbox" checked={settings.autoDetectCategory} onChange={e=>persistSettings({...settings,autoDetectCategory:e.target.checked})}/> Auto detect category</label><label><input type="checkbox" checked={settings.autofillFocusedInputFirst} onChange={e=>persistSettings({...settings,autofillFocusedInputFirst:e.target.checked})}/> Use focused email input first</label><label><input type="checkbox" checked={settings.fallbackToCopyWhenNoInput} onChange={e=>persistSettings({...settings,fallbackToCopyWhenNoInput:e.target.checked})}/> Copy if no input found</label><label>Gmail account index</label><input type="number" value={settings.gmailAccountIndex} onChange={e=>persistSettings({...settings,gmailAccountIndex:Number(e.target.value)})}/><div className="actions"><button onClick={exportJson}>Export data</button><button onClick={importJson}>Import data</button><button onClick={async()=>confirm('Clear all local alias manager data?')&&browser.storage.local.remove(['siteAliases','recentAliases','favoriteAliases'])}>Clear local data</button></div></section><Privacy/><Toast text={toast}/></div>;
  return <div className="app"><Header setView={setView}/><section className="card"><p className="label">Current site</p>{hostname?<strong>{hostname}</strong>:<><p className="muted">Manual mode: current page is not supported.</p><input placeholder="github.com" value={manualHost} onChange={e=>setManualHost(e.target.value.toLowerCase())}/></>}{!baseEmail && <p className="warn">Add a base Gmail account in Settings first.</p>}{previous && <div className="previous"><p className="label">Previously used for this site</p><strong>{previous.alias}</strong><div className="actions"><button onClick={()=>autofill(previous.alias)}>Autofill again</button><button onClick={()=>copy(previous.alias)}>Copy</button>{(['important','spam','leaked'] as AliasStatus[]).map(s=><button key={s} onClick={async()=>{await updateAliasStatus(previous.hostname,s); setAliases({...aliases,[previous.hostname]:{...previous,status:s}})}}>Mark {s}</button>)}</div>{['spam','leaked'].includes(previous.status)&&<p className="warn">This alias may have been shared or leaked. Consider creating a new alias for this website.</p>}</div>}<p className="label">Suggested alias</p><div className="aliasBox">{selected || 'No alias available'}</div><div className="actions"><button disabled={!selected} onClick={()=>autofill()}>Autofill</button><button disabled={!selected} onClick={()=>copy()}>Copy</button><button disabled={!selected || !activeHost} onClick={()=>save()}>Save</button></div><input placeholder="Optional purpose tag" value={purpose} onChange={e=>setPurpose(e.target.value)}/>{suggestions.length>1&&<><p className="label">Other suggestions</p>{suggestions.slice(1).map(s=><div className="suggestion" key={s.alias}><span>{s.alias}</span><button onClick={()=>save(s.alias)}>Save</button></div>)}</>}{quality&&<div className="info"><b>Alias quality:</b> {quality.label} ({quality.score})<br/><b>Tracking quality:</b> {quality.trackingLevel}<br/><b>Privacy level:</b> Basic<br/><span>{quality.warnings[0]}</span></div>}{selected&&<div className="info"><b>Gmail filter suggestion</b><br/>To: {selected}<br/>Apply label: {suggestedGmailLabel(category)}<br/>Optional: Skip Inbox<div className="actions"><button onClick={()=>copy(buildGmailFilterQuery(selected))}>Copy filter query</button><button onClick={()=>browser.tabs.create({url:buildGmailSearchUrl(selected,settings.gmailAccountIndex)})}>Open Gmail search</button></div></div>}</section><Privacy/><Toast text={toast}/></div>;
}
function Header({setView}:{setView:(v:'popup'|'dashboard'|'settings')=>void}){return <header><h1>Gmail Alias Toolkit</h1><p>Local-first Gmail plus alias manager</p><nav><button onClick={()=>setView('popup')}>Popup</button><button onClick={()=>setView('dashboard')}>Dashboard</button><button onClick={()=>setView('settings')}>Settings</button></nav></header>}
function Privacy(){return <section className="privacy"><b>Privacy</b><br/>No account required. No server. No tracking. Alias data is stored locally in your browser.<br/>Gmail plus aliases help with filtering and tracking, but they do not hide your real Gmail address.</section>}
function Toast({text}:{text:string}){return text?<div className="toast">{text}</div>:null}
