version = 1

exclude_patterns = [
  ".github/**",
  ".output/**",
  ".yarn/**",
  "**/_locales/**",
  "CHANGELOG.md",
  "README.md",
  "LICENSE",
  "docs/**",
  "public/**",
  "web/public/**",
  "web/src/phase-two/ProductTour.tsx",
  "yarn.lock",
  "src/components/motion/**",
]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]

[[transformers]]
name = "prettier"
