name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  ci:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --immutable --mode=skip-build

      - name: Prepare WXT types
        run: yarn exec wxt prepare

      - name: Build extension
        run: yarn build
